twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: 'Mon Application'
        app_version: '1.0.0'
    
    form_themes: ['bootstrap_5_layout.html.twig']
    
    # Pour les assets
    paths:
        '%kernel.project_dir%/public/assets': assets