# config/routes.yaml

# Route d'accueil principale
home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

# Import automatique de TOUS les contrôleurs
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Import des routes d'un bundle (si nécessaire)
# web_profiler:
#     resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
#     prefix: /_profiler